version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - WORKDIR=/usr/app
    restart: always
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - ./:/usr/app:rw
    environment:
      - NODE_ENV=development

  db:
    image: mongo:5.0
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db:rw
