version: '3.8'

services:
  db:
    image: mongo:5.0
    restart: always
    ports:
      - 27017:27017
    volumes:
      - db:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - WORKDIR=/usr/app
    restart: always
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - ./:/usr/app
      - node_modules:/usr/app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - db

volumes:
  node_modules:
  db:
